# name: Python Package CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#   test:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Install pytest
#         run: |
#           python -m pip install pytest
#           python -m pip install pytest-cov
#           python -m pip install requests

#       - name: Run Tests with Coverage
#         run: |
#           pytest --cov=./ --cov-report=xml

#       - name: Use Codecov to track coverage
#         uses: codecov/codecov-action@v2
#         with:
#           files: ./coverage.xml
#   deploy:
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Build and Publish Package
#         run: |
#           python setup.py sdist bdist_wheel
#           python -m pip install --upgrade twine
#           python -m twine upload dist/*
#         env:
#           TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
#           TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}



name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=python-package --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml   # coverage report

    - name: Build documentation
      run: poetry run make html --directory docs/

